package interfaces;
import controle.ControladorConsultaEmbarque;
import entidades.Pidion;
import entidades.Data;
import entidades.EmbarquePesquisa;
import entidades.Usuário;
import entidades.Visão;
import java.util.Vector;
import javax.swing.ButtonModel;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

public class JanelaConsultaEmbarque extends javax.swing.JFrame {
    ControladorConsultaEmbarque controlador;
    Vector<Visão<String>> lista_pidion ;
    Vector<Visão<String>> lista_usuário ;
    Data data_até = null;
    public JanelaConsultaEmbarque(ControladorConsultaEmbarque controlador) {
        this.controlador = controlador;       
        Visão<String> aux = new Visão("-1","Todos");
        lista_pidion = Pidion.getVisões();
        lista_pidion.add(aux);
        lista_usuário = Usuário.getVisões();       
        lista_usuário.add(aux);        
        initComponents();
        ComboBoxPidion.setSelectedItem(aux);
        ComboBoxUsu.setSelectedItem(aux);

    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanelSenha1 = new javax.swing.JPanel();
        jLabelPesquisar = new javax.swing.JLabel();
        jButtonBuscar = new javax.swing.JButton();
        jPanelNome = new javax.swing.JPanel();
        jLabelData_Embarque = new javax.swing.JLabel();
        FormattedTextFieldData = new javax.swing.JFormattedTextField();
        jLabelLocal_Embarque = new javax.swing.JLabel();
        jTextLocal_Embarque = new javax.swing.JTextField();
        jLabelCidade = new javax.swing.JLabel();
        jTextCidade = new javax.swing.JTextField();
        FormattedTextFieldDataAté = new javax.swing.JFormattedTextField();
        jLabel1 = new javax.swing.JLabel();
        jPanelProfissão1 = new javax.swing.JPanel();
        jTextVolume_Embarque = new javax.swing.JTextField();
        jLabelVolume_Embarque = new javax.swing.JLabel();
        jLabelSituação = new javax.swing.JLabel();
        jRadioButtonTodos = new javax.swing.JTextField();
        jLabelOS = new javax.swing.JLabel();
        jRadioButtonEmbarcando = new javax.swing.JRadioButton();
        jRadioButtonSuspenso = new javax.swing.JRadioButton();
        jRadioButton1 = new javax.swing.JRadioButton();
        jPanelProfissão = new javax.swing.JPanel();
        jLabelPidion = new javax.swing.JLabel();
        ComboBoxUsu = new javax.swing.JComboBox<>();
        ComboBoxPidion = new javax.swing.JComboBox<>();
        jLabelPidion1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jPanelProfissão2 = new javax.swing.JPanel();
        jTextVolume_Embarque1 = new javax.swing.JTextField();
        jLabelVolume_Embarque1 = new javax.swing.JLabel();
        jLabelOS1 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Consulta de Embarque");
        setLocation(new java.awt.Point(0, 0));
        setLocationByPlatform(true);
        setMaximumSize(new java.awt.Dimension(710, 600));
        setMinimumSize(new java.awt.Dimension(710, 600));
        setPreferredSize(new java.awt.Dimension(710, 600));
        setResizable(false);
        setSize(new java.awt.Dimension(710, 600));
        setType(java.awt.Window.Type.UTILITY);

        jLabelPesquisar.setText("Preencha os campos que deseja consultar e clique em buscar");

        jButtonBuscar.setText("Buscar");
        jButtonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarActionPerformed(evt);
            }
        });

        jLabelData_Embarque.setText("De");

        try {
            FormattedTextFieldData.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        FormattedTextFieldData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FormattedTextFieldDataActionPerformed(evt);
            }
        });

        jLabelLocal_Embarque.setText("Local de Embarque");

        jTextLocal_Embarque.setToolTipText("");
        jTextLocal_Embarque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextLocal_EmbarqueActionPerformed(evt);
            }
        });

        jLabelCidade.setText("Cidade");

        jTextCidade.setToolTipText("");
        jTextCidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextCidadeActionPerformed(evt);
            }
        });

        try {
            FormattedTextFieldDataAté.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        FormattedTextFieldDataAté.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FormattedTextFieldDataAtéActionPerformed(evt);
            }
        });

        jLabel1.setText("Até");

        javax.swing.GroupLayout jPanelNomeLayout = new javax.swing.GroupLayout(jPanelNome);
        jPanelNome.setLayout(jPanelNomeLayout);
        jPanelNomeLayout.setHorizontalGroup(
            jPanelNomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelNomeLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanelNomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(FormattedTextFieldData, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelData_Embarque))
                .addGap(18, 18, 18)
                .addGroup(jPanelNomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(FormattedTextFieldDataAté, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanelNomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelLocal_Embarque)
                    .addComponent(jTextLocal_Embarque, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelNomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelCidade)
                    .addComponent(jTextCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelNomeLayout.setVerticalGroup(
            jPanelNomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelNomeLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelNomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelData_Embarque)
                    .addComponent(jLabelLocal_Embarque)
                    .addComponent(jLabelCidade)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelNomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FormattedTextFieldData, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextLocal_Embarque, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FormattedTextFieldDataAté, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29))
        );

        jPanelProfissão1.setMaximumSize(new java.awt.Dimension(500, 500));
        jPanelProfissão1.setMinimumSize(new java.awt.Dimension(500, 500));
        jPanelProfissão1.setName(""); // NOI18N

        jLabelVolume_Embarque.setText("Volume do Embarque");

        jLabelSituação.setText("Situação");

        jRadioButtonTodos.setToolTipText("");
        jRadioButtonTodos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonTodosActionPerformed(evt);
            }
        });

        jLabelOS.setText("OS:");

        buttonGroup1.add(jRadioButtonEmbarcando);
        jRadioButtonEmbarcando.setText("Embarcando");
        jRadioButtonEmbarcando.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonEmbarcandoActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButtonSuspenso);
        jRadioButtonSuspenso.setText("Suspenso");

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setText("Todos");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelProfissão1Layout = new javax.swing.GroupLayout(jPanelProfissão1);
        jPanelProfissão1.setLayout(jPanelProfissão1Layout);
        jPanelProfissão1Layout.setHorizontalGroup(
            jPanelProfissão1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelProfissão1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanelProfissão1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextVolume_Embarque, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelVolume_Embarque))
                .addGap(19, 19, 19)
                .addGroup(jPanelProfissão1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelProfissão1Layout.createSequentialGroup()
                        .addComponent(jRadioButtonEmbarcando)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButtonSuspenso)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 6, Short.MAX_VALUE)
                        .addComponent(jRadioButton1))
                    .addGroup(jPanelProfissão1Layout.createSequentialGroup()
                        .addComponent(jLabelSituação)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelProfissão1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadioButtonTodos, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelOS))
                .addGap(22, 22, 22))
        );
        jPanelProfissão1Layout.setVerticalGroup(
            jPanelProfissão1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelProfissão1Layout.createSequentialGroup()
                .addGroup(jPanelProfissão1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelVolume_Embarque)
                    .addComponent(jLabelSituação)
                    .addComponent(jLabelOS))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelProfissão1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextVolume_Embarque, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRadioButtonTodos, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRadioButtonEmbarcando)
                    .addComponent(jRadioButtonSuspenso)
                    .addComponent(jRadioButton1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelProfissão.setMaximumSize(new java.awt.Dimension(500, 500));
        jPanelProfissão.setMinimumSize(new java.awt.Dimension(500, 500));
        jPanelProfissão.setName(""); // NOI18N

        jLabelPidion.setText("Usuário");

        ComboBoxUsu.setModel(new DefaultComboBoxModel (lista_usuário));

        ComboBoxPidion.setModel(new DefaultComboBoxModel (lista_pidion));

        jLabelPidion1.setText("Pidion");

        javax.swing.GroupLayout jPanelProfissãoLayout = new javax.swing.GroupLayout(jPanelProfissão);
        jPanelProfissão.setLayout(jPanelProfissãoLayout);
        jPanelProfissãoLayout.setHorizontalGroup(
            jPanelProfissãoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelProfissãoLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanelProfissãoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ComboBoxUsu, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelPidion, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(55, 55, 55)
                .addGroup(jPanelProfissãoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ComboBoxPidion, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelPidion1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelProfissãoLayout.setVerticalGroup(
            jPanelProfissãoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelProfissãoLayout.createSequentialGroup()
                .addGroup(jPanelProfissãoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelPidion)
                    .addComponent(jLabelPidion1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelProfissãoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ComboBoxUsu, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ComboBoxPidion, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(411, 411, 411))
        );

        jButton1.setText("Limpar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelSenha1Layout = new javax.swing.GroupLayout(jPanelSenha1);
        jPanelSenha1.setLayout(jPanelSenha1Layout);
        jPanelSenha1Layout.setHorizontalGroup(
            jPanelSenha1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelNome, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanelSenha1Layout.createSequentialGroup()
                .addGroup(jPanelSenha1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelSenha1Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jLabelPesquisar)
                        .addGap(44, 44, 44)
                        .addComponent(jButtonBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelSenha1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanelProfissão, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelSenha1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanelProfissão1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelSenha1Layout.setVerticalGroup(
            jPanelSenha1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSenha1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanelSenha1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelPesquisar)
                    .addComponent(jButtonBuscar)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanelNome, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanelProfissão1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelProfissão, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jPanelProfissão2.setMaximumSize(new java.awt.Dimension(500, 500));
        jPanelProfissão2.setMinimumSize(new java.awt.Dimension(500, 500));
        jPanelProfissão2.setName(""); // NOI18N

        jTextVolume_Embarque1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextVolume_Embarque1ActionPerformed(evt);
            }
        });

        jLabelVolume_Embarque1.setText("Profissão");

        jLabelOS1.setText("Impressora:");

        jCheckBox1.setText("HP Officejet 100");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });

        jCheckBox2.setText("HP Officejet 200");

        javax.swing.GroupLayout jPanelProfissão2Layout = new javax.swing.GroupLayout(jPanelProfissão2);
        jPanelProfissão2.setLayout(jPanelProfissão2Layout);
        jPanelProfissão2Layout.setHorizontalGroup(
            jPanelProfissão2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelProfissão2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanelProfissão2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextVolume_Embarque1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelVolume_Embarque1))
                .addGap(28, 28, 28)
                .addGroup(jPanelProfissão2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelOS1)
                    .addGroup(jPanelProfissão2Layout.createSequentialGroup()
                        .addComponent(jCheckBox1)
                        .addGap(18, 18, 18)
                        .addComponent(jCheckBox2)))
                .addContainerGap(99, Short.MAX_VALUE))
        );
        jPanelProfissão2Layout.setVerticalGroup(
            jPanelProfissão2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelProfissão2Layout.createSequentialGroup()
                .addGroup(jPanelProfissão2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelVolume_Embarque1)
                    .addComponent(jLabelOS1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelProfissão2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextVolume_Embarque1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCheckBox1)
                    .addComponent(jCheckBox2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelSenha1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 643, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jPanelProfissão2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(291, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelSenha1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanelProfissão2, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButtonTodosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonTodosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonTodosActionPerformed

    private void jTextLocal_EmbarqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextLocal_EmbarqueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextLocal_EmbarqueActionPerformed

    private void jTextCidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextCidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextCidadeActionPerformed

    private void FormattedTextFieldDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FormattedTextFieldDataActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FormattedTextFieldDataActionPerformed

    private void jButtonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarActionPerformed
        
        EmbarquePesquisa embarque = obterEmbarqueInformado();
        if(embarque!=null){
            Vector <EmbarquePesquisa> embarque1 = EmbarquePesquisa.buscaEmbarqueFiltro(embarque,data_até);
            String dados;

            jTextArea1.setText(null);
            dados = "Embarques Cadastrados:\n\n";
            if (embarque1 != null){        
                for (int i=0; i < embarque1.size() ; i++){
                    dados = dados + embarque1.get(i).toString();  
                    dados = dados + "\n\n";
                }

            }else{
                dados = dados + "Nenhum embarque cadastrado!";
            }
            jTextArea1.setText(dados);
        }else{
            JOptionPane.showMessageDialog(this,"Informe pelo menos a data para consulta!","ERRO",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButtonBuscarActionPerformed

    private void FormattedTextFieldDataAtéActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FormattedTextFieldDataAtéActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FormattedTextFieldDataAtéActionPerformed

    private void jRadioButtonEmbarcandoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonEmbarcandoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonEmbarcandoActionPerformed

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void jTextVolume_Embarque1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextVolume_Embarque1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextVolume_Embarque1ActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        FormattedTextFieldData.setText("");
        FormattedTextFieldDataAté.setText("");
        jRadioButtonTodos.setText("");
        jTextLocal_Embarque.setText("");
        ComboBoxPidion.setSelectedItem("Todos");
        jTextVolume_Embarque.setText("");
        ComboBoxUsu.setSelectedItem("Todos");  
        jTextVolume_Embarque1.setText("");

    }//GEN-LAST:event_jButton1ActionPerformed

    private EmbarquePesquisa obterEmbarqueInformado(){
        Data data_de = null;

        String data1 = FormattedTextFieldData.getText();
        if (data1.equals("  /  /    ")){ 
            data1 = null;
        }else{
            String[] splitted = data1.split("/");
            data_de = new Data(splitted[0],splitted[1],splitted[2]);
        }
        
        String data = FormattedTextFieldDataAté.getText();
        if (data.equals("  /  /    ")){ 
            data = null;
        }else{
            String[] splitted = data.split("/");
            data_até = new Data(splitted[0],splitted[1],splitted[2]);
        }
        
        String OS = jRadioButtonTodos.getText();
        if (OS.isEmpty()) OS = "-1";
        
        String local_Embarque = jTextLocal_Embarque.getText();
        if (local_Embarque.isEmpty()) local_Embarque = null;

        String cidade = jTextCidade.getText();
        if (cidade.isEmpty()) cidade = null;

        String pidion = null;
        pidion =  String.valueOf(ComboBoxPidion.getSelectedItem());
        if (pidion.equals("Todos")){
           pidion=null;
        }else{
            String Split[] = pidion.split("-");
            pidion = Split[0];
        }
        String volume_Embarque = jTextVolume_Embarque.getText();
        if (volume_Embarque.isEmpty()) volume_Embarque = "-1";
      
        String situação=null;
        if(jRadioButtonEmbarcando.isSelected()){
            situação = "Embarcando";
        }else if(jRadioButtonSuspenso.isSelected()){
            situação = "Suspenso";
        }
         
        
        if (situação==null) situação = null;
        
        String visão1 =  String.valueOf(lista_usuário.get(ComboBoxUsu.getSelectedIndex()).getChave());
        if (visão1 == null) visão1 = null;

        String profissão = jTextVolume_Embarque1.getText();
        if (profissão.isEmpty()) profissão = null;
        
        String impressora = null;
        if(jCheckBox1.isSelected() && jCheckBox2.isSelected()){
            impressora = null;
        }else if(jCheckBox1.isSelected()){
            impressora = "HP OfficeJet 100";
        }else if(jCheckBox2.isSelected()){
            impressora = "HP OfficeJet 200";
        }
        
       return new EmbarquePesquisa(0,data_de,Integer.valueOf(OS),local_Embarque,cidade,pidion, Float.valueOf(volume_Embarque), situação, visão1,profissão,impressora);      
    }
    

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JanelaConsultaEmbarque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JanelaConsultaEmbarque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JanelaConsultaEmbarque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JanelaConsultaEmbarque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>


    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ComboBoxPidion;
    private javax.swing.JComboBox<String> ComboBoxUsu;
    private javax.swing.JFormattedTextField FormattedTextFieldData;
    private javax.swing.JFormattedTextField FormattedTextFieldDataAté;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonBuscar;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelCidade;
    private javax.swing.JLabel jLabelData_Embarque;
    private javax.swing.JLabel jLabelLocal_Embarque;
    private javax.swing.JLabel jLabelOS;
    private javax.swing.JLabel jLabelOS1;
    private javax.swing.JLabel jLabelPesquisar;
    private javax.swing.JLabel jLabelPidion;
    private javax.swing.JLabel jLabelPidion1;
    private javax.swing.JLabel jLabelSituação;
    private javax.swing.JLabel jLabelVolume_Embarque;
    private javax.swing.JLabel jLabelVolume_Embarque1;
    private javax.swing.JPanel jPanelNome;
    private javax.swing.JPanel jPanelProfissão;
    private javax.swing.JPanel jPanelProfissão1;
    private javax.swing.JPanel jPanelProfissão2;
    private javax.swing.JPanel jPanelSenha1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButtonEmbarcando;
    private javax.swing.JRadioButton jRadioButtonSuspenso;
    private javax.swing.JTextField jRadioButtonTodos;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextCidade;
    private javax.swing.JTextField jTextLocal_Embarque;
    private javax.swing.JTextField jTextVolume_Embarque;
    private javax.swing.JTextField jTextVolume_Embarque1;
    // End of variables declaration//GEN-END:variables
}
