/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces;
import controle.ControladorCadastroUsuário;
import controle.ControladorCadastroPidion;
import controle.ControladorCadastroEmbarque;
import controle.ControladorConsultaEmbarque;
import persistência.BD;
/**
 *
 * @author Douglas
 */
public class JanelaConexãonocampo extends javax.swing.JFrame {

    /**
     * Creates new form JanelaConexãonocampo
     */
    public JanelaConexãonocampo() {
        BD.criaConexão();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        conexãocampoMenuBar = new javax.swing.JMenuBar();
        Cadastrar = new javax.swing.JMenu();
        UsuárioMenuItem = new javax.swing.JMenuItem();
        PidionMenuItem = new javax.swing.JMenuItem();
        Embarque = new javax.swing.JMenuItem();
        AlterarMenu = new javax.swing.JMenu();
        MenuEmbarque = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Conexão no Campo");
        setAlwaysOnTop(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        Cadastrar.setText("Cadastrar");

        UsuárioMenuItem.setText("Usuário");
        UsuárioMenuItem.setToolTipText("");
        UsuárioMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UsuárioMenuItemActionPerformed(evt);
            }
        });
        Cadastrar.add(UsuárioMenuItem);

        PidionMenuItem.setText("Pidion");
        PidionMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PidionMenuItemActionPerformed(evt);
            }
        });
        Cadastrar.add(PidionMenuItem);

        Embarque.setText("Embarque");
        Embarque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmbarqueActionPerformed(evt);
            }
        });
        Cadastrar.add(Embarque);

        conexãocampoMenuBar.add(Cadastrar);

        AlterarMenu.setText("Pesquisa");

        MenuEmbarque.setText("Embarque");
        MenuEmbarque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuEmbarqueActionPerformed(evt);
            }
        });
        AlterarMenu.add(MenuEmbarque);

        conexãocampoMenuBar.add(AlterarMenu);

        setJMenuBar(conexãocampoMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void UsuárioMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UsuárioMenuItemActionPerformed
        new ControladorCadastroUsuário();
    }//GEN-LAST:event_UsuárioMenuItemActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        BD.fechaConexão();        
        System.exit(1);
    }//GEN-LAST:event_formWindowClosed

    private void PidionMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PidionMenuItemActionPerformed
        new ControladorCadastroPidion();
    }//GEN-LAST:event_PidionMenuItemActionPerformed

    private void EmbarqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmbarqueActionPerformed
        new ControladorCadastroEmbarque();
    }//GEN-LAST:event_EmbarqueActionPerformed

    private void MenuEmbarqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuEmbarqueActionPerformed
        new ControladorConsultaEmbarque();
    }//GEN-LAST:event_MenuEmbarqueActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JanelaConexãonocampo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JanelaConexãonocampo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JanelaConexãonocampo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JanelaConexãonocampo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JanelaConexãonocampo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu AlterarMenu;
    private javax.swing.JMenu Cadastrar;
    private javax.swing.JMenuItem Embarque;
    private javax.swing.JMenuItem MenuEmbarque;
    private javax.swing.JMenuItem PidionMenuItem;
    private javax.swing.JMenuItem UsuárioMenuItem;
    private javax.swing.JMenuBar conexãocampoMenuBar;
    // End of variables declaration//GEN-END:variables
}
